DROP TABLE IF EXISTS AGENTS;
CREATE TABLE AGENTS (id INT NOT NULL PRIMARY KEY , skill_sets VARCHAR(50) NOT NULL);
COMMIT;

DROP TABLE IF EXISTS TASK;
CREATE TABLE TASK (task_id VARCHAR(50) NOT NULL PRIMARY KEY , skill_set VARCHAR(50) NOT NULL , agent_Id INT , priority VARCHAR(50) NOT NULL , status VARCHAR(10) NOT NULL, task_Date TIMESTAMP NOT NULL);
